# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.author }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "wRiteUpS"
author: "Bani"
description: >- # this means to ignore newlines until "baseurl:"
  A collection of my solutions and walkthroughs for various CTF challenges. 
  Feel free to explore the writeups!
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
markdown: kramdown
